apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-applicationset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: default
      - namespace: test2
  template:
    metadata:
      name: '{{namespace}}-leader'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      project: default
      source:
        kustomize:
          namePrefix: "{{namespace}}-"
          patches:
            - target:
                group: "argoproj.io"
                version: "v1alpha1"
                kind: "Application"
                name: .*
              patch: |-
                - op: add
                  path: /spec/source/kustomize/namespace
                  value: '{{namespace}}'
        path: appset/group
        repoURL: https://github.com/cla9/argocd-test
        targetRevision: main
      syncPolicy:
        automated: { }
        syncOptions:
          - CreateNamespace=true