apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx2
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      namespace: test2
    path: nginx1/overlay/dev
    repoURL: https://github.com/cla9/argocd-test
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true