resources:
  - ../../group/nginx1.yaml
  - ../../group/nginx2.yaml

patches:
  - target:
      group: "argoproj.io"
      version: "v1alpha1"
      kind: "Application"
      name: .*
    patch: |-
      - op: add
        path: /spec/source/kustomize/namespace
        value: test2
        
