{{ if .Values.nginx1.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: nginx1/overlay/dev
    repoURL: https://github.com/cla9/argocd-test
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
{{ end }}