apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx3-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      generatorOptions:
        disableNameSuffixHash: true

      configMapGenerator:
        - behavior: replace
          name: nginx2
          files:
            - ./dev/test2/configmap2.yaml
    path: nginx3/overlay/dev/base
    repoURL: https://github.com/cla9/argocd-test
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true