apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx3-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx3
  project: default
  source:
    kustomize:
      namespace: nginx3
      patches:
        - target:
            kind: ConfigMap
            name: nginx3
          path: "./test2/configmap2.yaml"
    path: nginx3/overlay/dev/base
    repoURL: https://github.com/cla9/argocd-test
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true